#!/bin/bash
# Purpose - A simple Bash function that backs up files according to a standardized naming convention.
# Modified by - Joseph Mark Orimoloye <cybonix@gmail.com>

# This function is not working...  I need to troubleshoot it.
function backup () {
	if [[ -z "$1" ]]; then
		echo "Usage: backup <filename>"
		return 1
	fi
	local date_stamp=$(date "+%Y-%m-%d.%H%M.bak");
	local newname="$1.$date_stamp";
	cp -p "$1" "$newname";
	echo "Backed up $1 to $newname.";
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	backup "$@"
fi
